name: allure
description: Allure Vanguard News App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.3.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^7.0.1
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  json_annotation: ^4.7.0
  persistent_bottom_nav_bar: ^5.0.2
  pretty_dio_logger: ^1.1.1
  shimmer: ^2.0.0
  timeago: ^3.3.0
  flutter_launcher_icons: ^0.11.0
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/category/
    - assets/profile/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
